hydra:
  run:
    dir: .
  output_subdir: null

exp_name: "qwen3_omni_rlvr"
seed: 42
logging_dir: ./output/logs
output_dir: ./output

# checkpoint_config:
#   type: mos

# track_with: ml_tracker
# tracker_kwargs:
#   project: ${exp_name}
#   notes: ${exp_name}
#   tags:
#     - roll
#     - rlvr
#     - qwen3-omni

save_steps: 20
logging_steps: 1
eval_steps: 10
resume_from_checkpoint: false

rollout_batch_size: 32 #256
num_return_sequences_in_group: 8
is_num_return_sequences_expand: true
prompt_length: 2048
response_length: 2048

ppo_epochs: 1
value_clip: 0.5
reward_clip: 10
advantage_clip: 10.0
whiten_advantages: false
init_kl_coef: 0.0
adv_estimator: "grpo"
use_kl_loss: true
kl_loss_coef: 1.0e-2

pretrain: Qwen/Qwen3-Omni-30B-A3B-Thinking
# pretrain: Qwen/Qwen3-Omni-30B-A3B-Instruct

#validation:
# data_args:
#   file_name:
#     - /data/oss_bucket_0/yuzhao/data/One-RL-to-See-Them-All/Orsta-Data-47k/test/test_math_megabench_237.parquet
#     - /data/oss_bucket_0/yuzhao/data/One-RL-to-See-Them-All/Orsta-Data-47k/test/test_detection_coco_test_multi_2000.parquet
#   dataset_dir: ./
# generating_args:
#   max_new_tokens: ${response_length}
#   top_p: 0.99
#   top_k: 100
#   num_beams: 1
#   temperature: 0.99
#   num_return_sequences: 1
# eval_steps: ${eval_steps}

actor_train:
  model_args:
    flash_attn: fa2
    attn_implementation: fa2
    disable_gradient_checkpointing: false
    dtype: bf16
    model_type: ~
    freeze_module_prefix: "vision_model,audio_model,talker,code2wav"
  training_args:
    learning_rate: 1.0e-6
    weight_decay: 1.0e-2
    per_device_train_batch_size: 1 #2
    gradient_accumulation_steps: 16 #16 #32
    warmup_steps: 0
    num_train_epochs: 50
  data_args:
    # case for training data: 
    # {
    #     "prompt": "Accurately transcribe the Polish audio into plain text.",
    #     "audios": ["dafd0ef215384e8b45326f43ee868204.wav"],
    #     "ability": "speech_recognition",
    #     "data_source": "the-mc-speech-dataset",
    #     "reward_model": {
    #         "answer": "Znajomy jest wiatr, woń zgniłych ryb, wodorostów i muszli.",
    #         "ground_truth": "Znajomy jest wiatr, woń zgniłych ryb, wodorostów i muszli.",
    #         "accuracy_ratio": 1.0,
    #         "format_ratio": 0.0,
    #         "verifier": "speech_recognition_verifier",
    #         "verifier_parm": {"test": "test"},
    #     },
    # }
    custom_data_kwargs_func: roll.datasets.vlm_dataset_utils.audio_test_get_data_kwargs
    file_name:
      - /data/oss_bucket_0/yuzhao/data/the-mc-speech-dataset-jsonl-format/data.jsonl
    audio_folder: /data/oss_bucket_0/yuzhao/data/the-mc-speech-dataset-jsonl-format/audios/
    domain_interleave_probs:
      math: 0.5
    dataset_dir: ./
    messages: prompt
    preprocessing_num_workers: 32
  strategy_args:
    strategy_name: megatron_train
    strategy_config:
      sequence_parallel: true
      tensor_model_parallel_size: 1
      context_parallel_size: 1
      expert_model_parallel_size: 8
      pipeline_model_parallel_size: 1
      use_distributed_optimizer: true
      # overlap_grad_reduce: true  # to be resolved
      moe_token_dispatcher_type: alltoall
      moe_grouped_gemm: true
      recompute_granularity: full
      bf16: true
  device_mapping: list(range(0,16))
  infer_batch_size: 1

actor_infer:
  model_args:
    flash_attn: fa2
    attn_implementation: fa2
    disable_gradient_checkpointing: true
    dtype: bf16
  generating_args:
    max_new_tokens: ${response_length}
    top_p: 0.99
    top_k: 100
    num_beams: 1
    temperature: 0.99
    num_return_sequences: ${num_return_sequences_in_group}
  strategy_args:
    strategy_name: vllm
    strategy_config:
      gpu_memory_utilization: 0.6
      block_size: 16
      max_model_len: 8192
      tensor_parallel_size: 4
      enforce_eager: true
      load_format: dummy
  num_gpus_per_worker: 4
  device_mapping: list(range(0,16))
  infer_batch_size: 2

reference:
  model_args:
    flash_attn: fa2
    attn_implementation: fa2
    disable_gradient_checkpointing: true
    dtype: bf16
    model_type: ~
  strategy_args:
    strategy_name: megatron_infer
    strategy_config:
      sequence_parallel: true
      tensor_model_parallel_size: 1
      context_parallel_size: 2
      pipeline_model_parallel_size: 1
      expert_model_parallel_size: 8
      bf16: true
  device_mapping: list(range(0,16))
  infer_batch_size: 2

rewards:
  math:
    # NOTE: dummy reward to run audio pipeline, should be replaced with real reward when training
    worker_cls: roll.pipeline.rlvr.rewards.math_rule_reward_worker.MathRuleRewardWorker
    model_args:
      model_name_or_path: ${pretrain}
    tag_included: [the-mc-speech-dataset]
    world_size: 8
    infer_batch_size: 1